### ISSUE TITLE
make upload_to_pypi configurable

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/wipac-dev-py-setup-action#12]
There are some projects where it's useful to run the setup action to fill in the default setup options and run python-semantic-release, but the project isn't meant to be published.  I'm thinking of server applications like WIPACrepo/user-management.

So, would be good to have an option to set `upload_to_pypi` to false, or at least not override what is manually set.

**Comment by ric-evans** [comment]
There are a few ways we can do this:
1. preserve the original `[semantic_release].upload_to_pypi` and don't override _only this attribute_
2. add an attribute to `[wipac:cicd_setup_builder]` like `upload_to_pypi`
3. Make `[wipac:cicd_setup_builder].pypi_name` optional, if it's present then `[semantic_release].upload_to_pypi=True`, otherwise set to `False`

I lean toward option 3, however, it's not as obvious as the previous options.

Other attributes/things that will be discluded by not enabling PyPI-publishing:
- `[metadata].download_url`
- the README's PyPI badge(s)

Thoughts?

**Comment by dsschult** [comment]
I have no preferences, so whichever is easiest.

**Comment by ric-evans** [comment]
I suppose it wouldn't make sense to include a `[metadata]` section in this case
